//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://webservice.civilfiling.ecourts.ito.aoc.nj/", ClrNamespace="webservice.civilfiling.ecourts.ito.aoc.nj")]



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/", ConfigurationName="CivilFilingWS")]
public interface CivilFilingWS
{
    
    // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/submitCivilFilingR" +
        "equest", ReplyAction="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/submitCivilFilingR" +
        "esponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(webservice.civilfiling.ecourts.ito.aoc.nj.ECourtsCivilServiceException), Action="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/submitCivilFiling/" +
        "Fault/ECourtsCivilServiceException", Name="ECourtsCivilServiceException")]
    [System.ServiceModel.FaultContractAttribute(typeof(webservice.civilfiling.ecourts.ito.aoc.nj.Exception), Action="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/submitCivilFiling/" +
        "Fault/Exception", Name="Exception")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    submitCivilFilingResponse submitCivilFiling(submitCivilFilingRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/submitCivilFilingR" +
        "equest", ReplyAction="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/submitCivilFilingR" +
        "esponse")]
    System.Threading.Tasks.Task<submitCivilFilingResponse> submitCivilFilingAsync(submitCivilFilingRequest request);
    
    // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/getCivilFilingStat" +
        "usRequest", ReplyAction="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/getCivilFilingStat" +
        "usResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(webservice.civilfiling.ecourts.ito.aoc.nj.ECourtsCivilServiceException), Action="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/getCivilFilingStat" +
        "us/Fault/ECourtsCivilServiceException", Name="ECourtsCivilServiceException")]
    [System.ServiceModel.FaultContractAttribute(typeof(webservice.civilfiling.ecourts.ito.aoc.nj.Exception), Action="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/getCivilFilingStat" +
        "us/Fault/Exception", Name="Exception")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    getCivilFilingStatusResponse getCivilFilingStatus(getCivilFilingStatusRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/getCivilFilingStat" +
        "usRequest", ReplyAction="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/getCivilFilingStat" +
        "usResponse")]
    System.Threading.Tasks.Task<getCivilFilingStatusResponse> getCivilFilingStatusAsync(getCivilFilingStatusRequest request);
    
    // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/searchNoticesReque" +
        "st", ReplyAction="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/searchNoticesRespo" +
        "nse")]
    [System.ServiceModel.FaultContractAttribute(typeof(webservice.civilfiling.ecourts.ito.aoc.nj.ECourtsCivilServiceException), Action="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/searchNotices/Faul" +
        "t/ECourtsCivilServiceException", Name="ECourtsCivilServiceException")]
    [System.ServiceModel.FaultContractAttribute(typeof(webservice.civilfiling.ecourts.ito.aoc.nj.Exception), Action="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/searchNotices/Faul" +
        "t/Exception", Name="Exception")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    searchNoticesResponse searchNotices(searchNoticesRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/searchNoticesReque" +
        "st", ReplyAction="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/searchNoticesRespo" +
        "nse")]
    System.Threading.Tasks.Task<searchNoticesResponse> searchNoticesAsync(searchNoticesRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
public partial class civilFilingRequest
{
    
    private bulkFilingPacket bulkFilingPacketField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public bulkFilingPacket bulkFilingPacket
    {
        get
        {
            return this.bulkFilingPacketField;
        }
        set
        {
            this.bulkFilingPacketField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
public partial class bulkFilingPacket
{
    
    private attachment[] attachmentListField;
    
    private string attorneyFirmIdField;
    
    private string attorneyIdField;
    
    private attribute[] attributesField;
    
    private @case civilCaseField;
    
    private party[] defendantListField;
    
    private string documentRedactionIndField;
    
    private efilingNumber efilingNumberField;
    
    private fee feeField;
    
    private party[] plaintiffListField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attachmentList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
    public attachment[] attachmentList
    {
        get
        {
            return this.attachmentListField;
        }
        set
        {
            this.attachmentListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string attorneyFirmId
    {
        get
        {
            return this.attorneyFirmIdField;
        }
        set
        {
            this.attorneyFirmIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string attorneyId
    {
        get
        {
            return this.attorneyIdField;
        }
        set
        {
            this.attorneyIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
    public attribute[] attributes
    {
        get
        {
            return this.attributesField;
        }
        set
        {
            this.attributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public @case civilCase
    {
        get
        {
            return this.civilCaseField;
        }
        set
        {
            this.civilCaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("defendantList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
    public party[] defendantList
    {
        get
        {
            return this.defendantListField;
        }
        set
        {
            this.defendantListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string documentRedactionInd
    {
        get
        {
            return this.documentRedactionIndField;
        }
        set
        {
            this.documentRedactionIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public efilingNumber efilingNumber
    {
        get
        {
            return this.efilingNumberField;
        }
        set
        {
            this.efilingNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
    public fee fee
    {
        get
        {
            return this.feeField;
        }
        set
        {
            this.feeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("plaintiffList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
    public party[] plaintiffList
    {
        get
        {
            return this.plaintiffListField;
        }
        set
        {
            this.plaintiffListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
public partial class attachment
{
    
    private attribute[] attributesField;
    
    private byte[] bytesField;
    
    private string contentTypeField;
    
    private string docTypeField;
    
    private string documentCodeField;
    
    private string documentDescriptionField;
    
    private string documentNameField;
    
    private string extentionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
    public attribute[] attributes
    {
        get
        {
            return this.attributesField;
        }
        set
        {
            this.attributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
    public byte[] bytes
    {
        get
        {
            return this.bytesField;
        }
        set
        {
            this.bytesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string contentType
    {
        get
        {
            return this.contentTypeField;
        }
        set
        {
            this.contentTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string docType
    {
        get
        {
            return this.docTypeField;
        }
        set
        {
            this.docTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string documentCode
    {
        get
        {
            return this.documentCodeField;
        }
        set
        {
            this.documentCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string documentDescription
    {
        get
        {
            return this.documentDescriptionField;
        }
        set
        {
            this.documentDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string documentName
    {
        get
        {
            return this.documentNameField;
        }
        set
        {
            this.documentNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public string extention
    {
        get
        {
            return this.extentionField;
        }
        set
        {
            this.extentionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
public partial class attribute
{
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
public partial class notice
{
    
    private attribute[] attributesField;
    
    private byte[] bytesField;
    
    private docketNumber docketNumberField;
    
    private string firmIdField;
    
    private string noticeDateField;
    
    private string noticeDescField;
    
    private string noticeTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
    public attribute[] attributes
    {
        get
        {
            return this.attributesField;
        }
        set
        {
            this.attributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
    public byte[] bytes
    {
        get
        {
            return this.bytesField;
        }
        set
        {
            this.bytesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public docketNumber docketNumber
    {
        get
        {
            return this.docketNumberField;
        }
        set
        {
            this.docketNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string firmId
    {
        get
        {
            return this.firmIdField;
        }
        set
        {
            this.firmIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string noticeDate
    {
        get
        {
            return this.noticeDateField;
        }
        set
        {
            this.noticeDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string noticeDesc
    {
        get
        {
            return this.noticeDescField;
        }
        set
        {
            this.noticeDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string noticeType
    {
        get
        {
            return this.noticeTypeField;
        }
        set
        {
            this.noticeTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
public partial class docketNumber
{
    
    private short docketCenturyYearField;
    
    private short docketCourtYearField;
    
    private long docketSeqNumField;
    
    private string docketTypeCodeField;
    
    private string docketVenueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public short docketCenturyYear
    {
        get
        {
            return this.docketCenturyYearField;
        }
        set
        {
            this.docketCenturyYearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public short docketCourtYear
    {
        get
        {
            return this.docketCourtYearField;
        }
        set
        {
            this.docketCourtYearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public long docketSeqNum
    {
        get
        {
            return this.docketSeqNumField;
        }
        set
        {
            this.docketSeqNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string docketTypeCode
    {
        get
        {
            return this.docketTypeCodeField;
        }
        set
        {
            this.docketTypeCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string docketVenue
    {
        get
        {
            return this.docketVenueField;
        }
        set
        {
            this.docketVenueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
public partial class noticeResponse
{
    
    private message[] messagesField;
    
    private notice[] noticesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("messages", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
    public message[] messages
    {
        get
        {
            return this.messagesField;
        }
        set
        {
            this.messagesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("notices", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
    public notice[] notices
    {
        get
        {
            return this.noticesField;
        }
        set
        {
            this.noticesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
public partial class message
{
    
    private string codeField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
public partial class noticeRequest
{
    
    private attribute[] attributesField;
    
    private string firmIdField;
    
    private string noticeDateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
    public attribute[] attributes
    {
        get
        {
            return this.attributesField;
        }
        set
        {
            this.attributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string firmId
    {
        get
        {
            return this.firmIdField;
        }
        set
        {
            this.firmIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string noticeDate
    {
        get
        {
            return this.noticeDateField;
        }
        set
        {
            this.noticeDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
public partial class civilFilingResponse
{
    
    private docketNumber docketNumberField;
    
    private efilingNumber efilingNumberField;
    
    private message[] messagesField;
    
    private bool queueFilingProcessedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public docketNumber docketNumber
    {
        get
        {
            return this.docketNumberField;
        }
        set
        {
            this.docketNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public efilingNumber efilingNumber
    {
        get
        {
            return this.efilingNumberField;
        }
        set
        {
            this.efilingNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("messages", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
    public message[] messages
    {
        get
        {
            return this.messagesField;
        }
        set
        {
            this.messagesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public bool queueFilingProcessed
    {
        get
        {
            return this.queueFilingProcessedField;
        }
        set
        {
            this.queueFilingProcessedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
public partial class efilingNumber
{
    
    private string efilingCourtDivField;
    
    private string efilingCourtYrField;
    
    private long efilingSeqNoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string efilingCourtDiv
    {
        get
        {
            return this.efilingCourtDivField;
        }
        set
        {
            this.efilingCourtDivField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string efilingCourtYr
    {
        get
        {
            return this.efilingCourtYrField;
        }
        set
        {
            this.efilingCourtYrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public long efilingSeqNo
    {
        get
        {
            return this.efilingSeqNoField;
        }
        set
        {
            this.efilingSeqNoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
public partial class fee
{
    
    private string accountNumberField;
    
    private string attorneyClientRefNumberField;
    
    private decimal attorneyFeeField;
    
    private bool attorneyFeeFieldSpecified;
    
    private attribute[] attributesField;
    
    private string exemptionReasonField;
    
    private string feeExemptField;
    
    private string paymentTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string accountNumber
    {
        get
        {
            return this.accountNumberField;
        }
        set
        {
            this.accountNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string attorneyClientRefNumber
    {
        get
        {
            return this.attorneyClientRefNumberField;
        }
        set
        {
            this.attorneyClientRefNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public decimal attorneyFee
    {
        get
        {
            return this.attorneyFeeField;
        }
        set
        {
            this.attorneyFeeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool attorneyFeeSpecified
    {
        get
        {
            return this.attorneyFeeFieldSpecified;
        }
        set
        {
            this.attorneyFeeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
    public attribute[] attributes
    {
        get
        {
            return this.attributesField;
        }
        set
        {
            this.attributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string exemptionReason
    {
        get
        {
            return this.exemptionReasonField;
        }
        set
        {
            this.exemptionReasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string feeExempt
    {
        get
        {
            return this.feeExemptField;
        }
        set
        {
            this.feeExemptField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string paymentType
    {
        get
        {
            return this.paymentTypeField;
        }
        set
        {
            this.paymentTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
public partial class partyAlias
{
    
    private string alternateNameField;
    
    private string alternateTypeCodeField;
    
    private attribute[] attributesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string alternateName
    {
        get
        {
            return this.alternateNameField;
        }
        set
        {
            this.alternateNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string alternateTypeCode
    {
        get
        {
            return this.alternateTypeCodeField;
        }
        set
        {
            this.alternateTypeCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
    public attribute[] attributes
    {
        get
        {
            return this.attributesField;
        }
        set
        {
            this.attributesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
public partial class name
{
    
    private string firstNameField;
    
    private string lastNameField;
    
    private string middleNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string firstName
    {
        get
        {
            return this.firstNameField;
        }
        set
        {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string lastName
    {
        get
        {
            return this.lastNameField;
        }
        set
        {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string middleName
    {
        get
        {
            return this.middleNameField;
        }
        set
        {
            this.middleNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
public partial class address
{
    
    private string addressLine1Field;
    
    private string addressLine2Field;
    
    private attribute[] attributesField;
    
    private string cityField;
    
    private string stateCodeField;
    
    private string zipCodeField;
    
    private string zipCodeExtField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string addressLine1
    {
        get
        {
            return this.addressLine1Field;
        }
        set
        {
            this.addressLine1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string addressLine2
    {
        get
        {
            return this.addressLine2Field;
        }
        set
        {
            this.addressLine2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
    public attribute[] attributes
    {
        get
        {
            return this.attributesField;
        }
        set
        {
            this.attributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string city
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string stateCode
    {
        get
        {
            return this.stateCodeField;
        }
        set
        {
            this.stateCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string zipCode
    {
        get
        {
            return this.zipCodeField;
        }
        set
        {
            this.zipCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string zipCodeExt
    {
        get
        {
            return this.zipCodeExtField;
        }
        set
        {
            this.zipCodeExtField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
public partial class party
{
    
    private string accommodationTypeField;
    
    private string adaAccommodationIndField;
    
    private string additionalAccommodationDetailsField;
    
    private address addressField;
    
    private attribute[] attributesField;
    
    private string corporationNameField;
    
    private string corporationTypeField;
    
    private string interpreterIndField;
    
    private string languageField;
    
    private name nameField;
    
    private string partyAffiliationField;
    
    private partyAlias[] partyAliasListField;
    
    private string partyDescriptionField;
    
    private string phoneNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string accommodationType
    {
        get
        {
            return this.accommodationTypeField;
        }
        set
        {
            this.accommodationTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string adaAccommodationInd
    {
        get
        {
            return this.adaAccommodationIndField;
        }
        set
        {
            this.adaAccommodationIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string additionalAccommodationDetails
    {
        get
        {
            return this.additionalAccommodationDetailsField;
        }
        set
        {
            this.additionalAccommodationDetailsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public address address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
    public attribute[] attributes
    {
        get
        {
            return this.attributesField;
        }
        set
        {
            this.attributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string corporationName
    {
        get
        {
            return this.corporationNameField;
        }
        set
        {
            this.corporationNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string corporationType
    {
        get
        {
            return this.corporationTypeField;
        }
        set
        {
            this.corporationTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public string interpreterInd
    {
        get
        {
            return this.interpreterIndField;
        }
        set
        {
            this.interpreterIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
    public string language
    {
        get
        {
            return this.languageField;
        }
        set
        {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
    public name name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
    public string partyAffiliation
    {
        get
        {
            return this.partyAffiliationField;
        }
        set
        {
            this.partyAffiliationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("partyAliasList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
    public partyAlias[] partyAliasList
    {
        get
        {
            return this.partyAliasListField;
        }
        set
        {
            this.partyAliasListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
    public string partyDescription
    {
        get
        {
            return this.partyDescriptionField;
        }
        set
        {
            this.partyDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
    public string phoneNumber
    {
        get
        {
            return this.phoneNumberField;
        }
        set
        {
            this.phoneNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
public partial class @case
{
    
    private attribute[] attributesField;
    
    private string caseActionField;
    
    private string courtSectionField;
    
    private string defendantCaptionField;
    
    private decimal demandAmountField;
    
    private bool demandAmountFieldSpecified;
    
    private string docketDetailsForOtherCourtField;
    
    private string juryDemandField;
    
    private string lawFirmCaseIdField;
    
    private string otherCourtActionsField;
    
    private string plaintiffCaptionField;
    
    private string serviceMethodField;
    
    private string venueField;
    
    private string venueOfIncidentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
    public attribute[] attributes
    {
        get
        {
            return this.attributesField;
        }
        set
        {
            this.attributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string caseAction
    {
        get
        {
            return this.caseActionField;
        }
        set
        {
            this.caseActionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string courtSection
    {
        get
        {
            return this.courtSectionField;
        }
        set
        {
            this.courtSectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string defendantCaption
    {
        get
        {
            return this.defendantCaptionField;
        }
        set
        {
            this.defendantCaptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public decimal demandAmount
    {
        get
        {
            return this.demandAmountField;
        }
        set
        {
            this.demandAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool demandAmountSpecified
    {
        get
        {
            return this.demandAmountFieldSpecified;
        }
        set
        {
            this.demandAmountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string docketDetailsForOtherCourt
    {
        get
        {
            return this.docketDetailsForOtherCourtField;
        }
        set
        {
            this.docketDetailsForOtherCourtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string juryDemand
    {
        get
        {
            return this.juryDemandField;
        }
        set
        {
            this.juryDemandField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public string lawFirmCaseId
    {
        get
        {
            return this.lawFirmCaseIdField;
        }
        set
        {
            this.lawFirmCaseIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
    public string otherCourtActions
    {
        get
        {
            return this.otherCourtActionsField;
        }
        set
        {
            this.otherCourtActionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
    public string plaintiffCaption
    {
        get
        {
            return this.plaintiffCaptionField;
        }
        set
        {
            this.plaintiffCaptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
    public string serviceMethod
    {
        get
        {
            return this.serviceMethodField;
        }
        set
        {
            this.serviceMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
    public string venue
    {
        get
        {
            return this.venueField;
        }
        set
        {
            this.venueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
    public string venueOfIncident
    {
        get
        {
            return this.venueOfIncidentField;
        }
        set
        {
            this.venueOfIncidentField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="submitCivilFiling", WrapperNamespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/", IsWrapped=true)]
public partial class submitCivilFilingRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public civilFilingRequest arg0;
    
    public submitCivilFilingRequest()
    {
    }
    
    public submitCivilFilingRequest(civilFilingRequest arg0)
    {
        this.arg0 = arg0;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="submitCivilFilingResponse", WrapperNamespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/", IsWrapped=true)]
public partial class submitCivilFilingResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public civilFilingResponse @return;
    
    public submitCivilFilingResponse()
    {
    }
    
    public submitCivilFilingResponse(civilFilingResponse @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getCivilFilingStatus", WrapperNamespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/", IsWrapped=true)]
public partial class getCivilFilingStatusRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public civilFilingRequest arg0;
    
    public getCivilFilingStatusRequest()
    {
    }
    
    public getCivilFilingStatusRequest(civilFilingRequest arg0)
    {
        this.arg0 = arg0;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getCivilFilingStatusResponse", WrapperNamespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/", IsWrapped=true)]
public partial class getCivilFilingStatusResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public civilFilingResponse @return;
    
    public getCivilFilingStatusResponse()
    {
    }
    
    public getCivilFilingStatusResponse(civilFilingResponse @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="searchNotices", WrapperNamespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/", IsWrapped=true)]
public partial class searchNoticesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public noticeRequest arg0;
    
    public searchNoticesRequest()
    {
    }
    
    public searchNoticesRequest(noticeRequest arg0)
    {
        this.arg0 = arg0;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="searchNoticesResponse", WrapperNamespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/", IsWrapped=true)]
public partial class searchNoticesResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public noticeResponse @return;
    
    public searchNoticesResponse()
    {
    }
    
    public searchNoticesResponse(noticeResponse @return)
    {
        this.@return = @return;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface CivilFilingWSChannel : CivilFilingWS, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CivilFilingWSClient : System.ServiceModel.ClientBase<CivilFilingWS>, CivilFilingWS
{
    
    public CivilFilingWSClient()
    {
    }
    
    public CivilFilingWSClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CivilFilingWSClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CivilFilingWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CivilFilingWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    submitCivilFilingResponse CivilFilingWS.submitCivilFiling(submitCivilFilingRequest request)
    {
        return base.Channel.submitCivilFiling(request);
    }
    
    public civilFilingResponse submitCivilFiling(civilFilingRequest arg0)
    {
        submitCivilFilingRequest inValue = new submitCivilFilingRequest();
        inValue.arg0 = arg0;
        submitCivilFilingResponse retVal = ((CivilFilingWS)(this)).submitCivilFiling(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<submitCivilFilingResponse> CivilFilingWS.submitCivilFilingAsync(submitCivilFilingRequest request)
    {
        return base.Channel.submitCivilFilingAsync(request);
    }
    
    public System.Threading.Tasks.Task<submitCivilFilingResponse> submitCivilFilingAsync(civilFilingRequest arg0)
    {
        submitCivilFilingRequest inValue = new submitCivilFilingRequest();
        inValue.arg0 = arg0;
        return ((CivilFilingWS)(this)).submitCivilFilingAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getCivilFilingStatusResponse CivilFilingWS.getCivilFilingStatus(getCivilFilingStatusRequest request)
    {
        return base.Channel.getCivilFilingStatus(request);
    }
    
    public civilFilingResponse getCivilFilingStatus(civilFilingRequest arg0)
    {
        getCivilFilingStatusRequest inValue = new getCivilFilingStatusRequest();
        inValue.arg0 = arg0;
        getCivilFilingStatusResponse retVal = ((CivilFilingWS)(this)).getCivilFilingStatus(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getCivilFilingStatusResponse> CivilFilingWS.getCivilFilingStatusAsync(getCivilFilingStatusRequest request)
    {
        return base.Channel.getCivilFilingStatusAsync(request);
    }
    
    public System.Threading.Tasks.Task<getCivilFilingStatusResponse> getCivilFilingStatusAsync(civilFilingRequest arg0)
    {
        getCivilFilingStatusRequest inValue = new getCivilFilingStatusRequest();
        inValue.arg0 = arg0;
        return ((CivilFilingWS)(this)).getCivilFilingStatusAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    searchNoticesResponse CivilFilingWS.searchNotices(searchNoticesRequest request)
    {
        return base.Channel.searchNotices(request);
    }
    
    public noticeResponse searchNotices(noticeRequest arg0)
    {
        searchNoticesRequest inValue = new searchNoticesRequest();
        inValue.arg0 = arg0;
        searchNoticesResponse retVal = ((CivilFilingWS)(this)).searchNotices(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<searchNoticesResponse> CivilFilingWS.searchNoticesAsync(searchNoticesRequest request)
    {
        return base.Channel.searchNoticesAsync(request);
    }
    
    public System.Threading.Tasks.Task<searchNoticesResponse> searchNoticesAsync(noticeRequest arg0)
    {
        searchNoticesRequest inValue = new searchNoticesRequest();
        inValue.arg0 = arg0;
        return ((CivilFilingWS)(this)).searchNoticesAsync(inValue);
    }
}
namespace webservice.civilfiling.ecourts.ito.aoc.nj
{
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class ECourtsCivilServiceException : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("ECourtsCivilServiceException", "http://webservice.civilfiling.ecourts.ito.aoc.nj/");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class Exception : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("Exception", "http://webservice.civilfiling.ecourts.ito.aoc.nj/");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
}
