//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivilFilingClient.CivilFilingServiceReference {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
    public partial class ECourtsCivilServiceException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private string messageCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string messageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
                this.RaisePropertyChanged("messageCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
    public partial class message : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
    public partial class docketNumber : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short docketCenturyYearField;
        
        private short docketCourtYearField;
        
        private long docketSeqNumField;
        
        private string docketTypeCodeField;
        
        private string docketVenueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public short docketCenturyYear {
            get {
                return this.docketCenturyYearField;
            }
            set {
                this.docketCenturyYearField = value;
                this.RaisePropertyChanged("docketCenturyYear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public short docketCourtYear {
            get {
                return this.docketCourtYearField;
            }
            set {
                this.docketCourtYearField = value;
                this.RaisePropertyChanged("docketCourtYear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long docketSeqNum {
            get {
                return this.docketSeqNumField;
            }
            set {
                this.docketSeqNumField = value;
                this.RaisePropertyChanged("docketSeqNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string docketTypeCode {
            get {
                return this.docketTypeCodeField;
            }
            set {
                this.docketTypeCodeField = value;
                this.RaisePropertyChanged("docketTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string docketVenue {
            get {
                return this.docketVenueField;
            }
            set {
                this.docketVenueField = value;
                this.RaisePropertyChanged("docketVenue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
    public partial class civilFilingResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private docketNumber docketNumberField;
        
        private efilingNumber efilingNumberField;
        
        private message[] messagesField;
        
        private bool queueFilingProcessedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public docketNumber docketNumber {
            get {
                return this.docketNumberField;
            }
            set {
                this.docketNumberField = value;
                this.RaisePropertyChanged("docketNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public efilingNumber efilingNumber {
            get {
                return this.efilingNumberField;
            }
            set {
                this.efilingNumberField = value;
                this.RaisePropertyChanged("efilingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messages", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public message[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
                this.RaisePropertyChanged("messages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool queueFilingProcessed {
            get {
                return this.queueFilingProcessedField;
            }
            set {
                this.queueFilingProcessedField = value;
                this.RaisePropertyChanged("queueFilingProcessed");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
    public partial class efilingNumber : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string efilingCourtDivField;
        
        private string efilingCourtYrField;
        
        private long efilingSeqNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string efilingCourtDiv {
            get {
                return this.efilingCourtDivField;
            }
            set {
                this.efilingCourtDivField = value;
                this.RaisePropertyChanged("efilingCourtDiv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string efilingCourtYr {
            get {
                return this.efilingCourtYrField;
            }
            set {
                this.efilingCourtYrField = value;
                this.RaisePropertyChanged("efilingCourtYr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long efilingSeqNo {
            get {
                return this.efilingSeqNoField;
            }
            set {
                this.efilingSeqNoField = value;
                this.RaisePropertyChanged("efilingSeqNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
    public partial class fee : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountNumberField;
        
        private string attorneyClientRefNumberField;
        
        private decimal attorneyFeeField;
        
        private bool attorneyFeeFieldSpecified;
        
        private attribute[] attributesField;
        
        private string exemptionReasonField;
        
        private string feeExemptField;
        
        private string paymentTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("accountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string attorneyClientRefNumber {
            get {
                return this.attorneyClientRefNumberField;
            }
            set {
                this.attorneyClientRefNumberField = value;
                this.RaisePropertyChanged("attorneyClientRefNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal attorneyFee {
            get {
                return this.attorneyFeeField;
            }
            set {
                this.attorneyFeeField = value;
                this.RaisePropertyChanged("attorneyFee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attorneyFeeSpecified {
            get {
                return this.attorneyFeeFieldSpecified;
            }
            set {
                this.attorneyFeeFieldSpecified = value;
                this.RaisePropertyChanged("attorneyFeeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public attribute[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
                this.RaisePropertyChanged("attributes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string exemptionReason {
            get {
                return this.exemptionReasonField;
            }
            set {
                this.exemptionReasonField = value;
                this.RaisePropertyChanged("exemptionReason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string feeExempt {
            get {
                return this.feeExemptField;
            }
            set {
                this.feeExemptField = value;
                this.RaisePropertyChanged("feeExempt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string paymentType {
            get {
                return this.paymentTypeField;
            }
            set {
                this.paymentTypeField = value;
                this.RaisePropertyChanged("paymentType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
    public partial class attribute : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
    public partial class partyAlias : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string alternateNameField;
        
        private string alternateTypeCodeField;
        
        private attribute[] attributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string alternateName {
            get {
                return this.alternateNameField;
            }
            set {
                this.alternateNameField = value;
                this.RaisePropertyChanged("alternateName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string alternateTypeCode {
            get {
                return this.alternateTypeCodeField;
            }
            set {
                this.alternateTypeCodeField = value;
                this.RaisePropertyChanged("alternateTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public attribute[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
                this.RaisePropertyChanged("attributes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
    public partial class name : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string middleNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string middleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
                this.RaisePropertyChanged("middleName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
    public partial class address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private attribute[] attributesField;
        
        private string cityField;
        
        private string stateCodeField;
        
        private string zipCodeField;
        
        private string zipCodeExtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string addressLine1 {
            get {
                return this.addressLine1Field;
            }
            set {
                this.addressLine1Field = value;
                this.RaisePropertyChanged("addressLine1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string addressLine2 {
            get {
                return this.addressLine2Field;
            }
            set {
                this.addressLine2Field = value;
                this.RaisePropertyChanged("addressLine2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public attribute[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
                this.RaisePropertyChanged("attributes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string stateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
                this.RaisePropertyChanged("stateCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("zipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string zipCodeExt {
            get {
                return this.zipCodeExtField;
            }
            set {
                this.zipCodeExtField = value;
                this.RaisePropertyChanged("zipCodeExt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
    public partial class party : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accommodationTypeField;
        
        private string adaAccommodationIndField;
        
        private string additionalAccommodationDetailsField;
        
        private address addressField;
        
        private attribute[] attributesField;
        
        private string corporationNameField;
        
        private string corporationTypeField;
        
        private string interpreterIndField;
        
        private string languageField;
        
        private name nameField;
        
        private string partyAffiliationField;
        
        private partyAlias[] partyAliasListField;
        
        private string partyDescriptionField;
        
        private string phoneNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string accommodationType {
            get {
                return this.accommodationTypeField;
            }
            set {
                this.accommodationTypeField = value;
                this.RaisePropertyChanged("accommodationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string adaAccommodationInd {
            get {
                return this.adaAccommodationIndField;
            }
            set {
                this.adaAccommodationIndField = value;
                this.RaisePropertyChanged("adaAccommodationInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string additionalAccommodationDetails {
            get {
                return this.additionalAccommodationDetailsField;
            }
            set {
                this.additionalAccommodationDetailsField = value;
                this.RaisePropertyChanged("additionalAccommodationDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public address address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public attribute[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
                this.RaisePropertyChanged("attributes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string corporationName {
            get {
                return this.corporationNameField;
            }
            set {
                this.corporationNameField = value;
                this.RaisePropertyChanged("corporationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string corporationType {
            get {
                return this.corporationTypeField;
            }
            set {
                this.corporationTypeField = value;
                this.RaisePropertyChanged("corporationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string interpreterInd {
            get {
                return this.interpreterIndField;
            }
            set {
                this.interpreterIndField = value;
                this.RaisePropertyChanged("interpreterInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public name name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string partyAffiliation {
            get {
                return this.partyAffiliationField;
            }
            set {
                this.partyAffiliationField = value;
                this.RaisePropertyChanged("partyAffiliation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("partyAliasList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public partyAlias[] partyAliasList {
            get {
                return this.partyAliasListField;
            }
            set {
                this.partyAliasListField = value;
                this.RaisePropertyChanged("partyAliasList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string partyDescription {
            get {
                return this.partyDescriptionField;
            }
            set {
                this.partyDescriptionField = value;
                this.RaisePropertyChanged("partyDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("phoneNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
    public partial class @case : object, System.ComponentModel.INotifyPropertyChanged {
        
        private attribute[] attributesField;
        
        private string caseActionField;
        
        private string courtSectionField;
        
        private string defendantCaptionField;
        
        private decimal demandAmountField;
        
        private bool demandAmountFieldSpecified;
        
        private string docketDetailsForOtherCourtField;
        
        private string juryDemandField;
        
        private string lawFirmCaseIdField;
        
        private string otherCourtActionsField;
        
        private string plaintiffCaptionField;
        
        private string serviceMethodField;
        
        private string venueField;
        
        private string venueOfIncidentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public attribute[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
                this.RaisePropertyChanged("attributes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string caseAction {
            get {
                return this.caseActionField;
            }
            set {
                this.caseActionField = value;
                this.RaisePropertyChanged("caseAction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string courtSection {
            get {
                return this.courtSectionField;
            }
            set {
                this.courtSectionField = value;
                this.RaisePropertyChanged("courtSection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string defendantCaption {
            get {
                return this.defendantCaptionField;
            }
            set {
                this.defendantCaptionField = value;
                this.RaisePropertyChanged("defendantCaption");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal demandAmount {
            get {
                return this.demandAmountField;
            }
            set {
                this.demandAmountField = value;
                this.RaisePropertyChanged("demandAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool demandAmountSpecified {
            get {
                return this.demandAmountFieldSpecified;
            }
            set {
                this.demandAmountFieldSpecified = value;
                this.RaisePropertyChanged("demandAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string docketDetailsForOtherCourt {
            get {
                return this.docketDetailsForOtherCourtField;
            }
            set {
                this.docketDetailsForOtherCourtField = value;
                this.RaisePropertyChanged("docketDetailsForOtherCourt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string juryDemand {
            get {
                return this.juryDemandField;
            }
            set {
                this.juryDemandField = value;
                this.RaisePropertyChanged("juryDemand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string lawFirmCaseId {
            get {
                return this.lawFirmCaseIdField;
            }
            set {
                this.lawFirmCaseIdField = value;
                this.RaisePropertyChanged("lawFirmCaseId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string otherCourtActions {
            get {
                return this.otherCourtActionsField;
            }
            set {
                this.otherCourtActionsField = value;
                this.RaisePropertyChanged("otherCourtActions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string plaintiffCaption {
            get {
                return this.plaintiffCaptionField;
            }
            set {
                this.plaintiffCaptionField = value;
                this.RaisePropertyChanged("plaintiffCaption");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string serviceMethod {
            get {
                return this.serviceMethodField;
            }
            set {
                this.serviceMethodField = value;
                this.RaisePropertyChanged("serviceMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string venue {
            get {
                return this.venueField;
            }
            set {
                this.venueField = value;
                this.RaisePropertyChanged("venue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string venueOfIncident {
            get {
                return this.venueOfIncidentField;
            }
            set {
                this.venueOfIncidentField = value;
                this.RaisePropertyChanged("venueOfIncident");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
    public partial class attachment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private attribute[] attributesField;
        
        private byte[] bytesField;
        
        private string contentTypeField;
        
        private string docTypeField;
        
        private string documentCodeField;
        
        private string documentDescriptionField;
        
        private string documentNameField;
        
        private string extentionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public attribute[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
                this.RaisePropertyChanged("attributes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] bytes {
            get {
                return this.bytesField;
            }
            set {
                this.bytesField = value;
                this.RaisePropertyChanged("bytes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string contentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
                this.RaisePropertyChanged("contentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string docType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
                this.RaisePropertyChanged("docType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string documentCode {
            get {
                return this.documentCodeField;
            }
            set {
                this.documentCodeField = value;
                this.RaisePropertyChanged("documentCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string documentDescription {
            get {
                return this.documentDescriptionField;
            }
            set {
                this.documentDescriptionField = value;
                this.RaisePropertyChanged("documentDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string documentName {
            get {
                return this.documentNameField;
            }
            set {
                this.documentNameField = value;
                this.RaisePropertyChanged("documentName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string extention {
            get {
                return this.extentionField;
            }
            set {
                this.extentionField = value;
                this.RaisePropertyChanged("extention");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
    public partial class bulkFilingPacket : object, System.ComponentModel.INotifyPropertyChanged {
        
        private attachment[] attachmentListField;
        
        private string attorneyFirmIdField;
        
        private string attorneyIdField;
        
        private attribute[] attributesField;
        
        private @case civilCaseField;
        
        private party[] defendantListField;
        
        private string documentRedactionIndField;
        
        private efilingNumber efilingNumberField;
        
        private fee feeField;
        
        private party[] plaintiffListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attachmentList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public attachment[] attachmentList {
            get {
                return this.attachmentListField;
            }
            set {
                this.attachmentListField = value;
                this.RaisePropertyChanged("attachmentList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string attorneyFirmId {
            get {
                return this.attorneyFirmIdField;
            }
            set {
                this.attorneyFirmIdField = value;
                this.RaisePropertyChanged("attorneyFirmId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string attorneyId {
            get {
                return this.attorneyIdField;
            }
            set {
                this.attorneyIdField = value;
                this.RaisePropertyChanged("attorneyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public attribute[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
                this.RaisePropertyChanged("attributes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public @case civilCase {
            get {
                return this.civilCaseField;
            }
            set {
                this.civilCaseField = value;
                this.RaisePropertyChanged("civilCase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("defendantList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public party[] defendantList {
            get {
                return this.defendantListField;
            }
            set {
                this.defendantListField = value;
                this.RaisePropertyChanged("defendantList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string documentRedactionInd {
            get {
                return this.documentRedactionIndField;
            }
            set {
                this.documentRedactionIndField = value;
                this.RaisePropertyChanged("documentRedactionInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public efilingNumber efilingNumber {
            get {
                return this.efilingNumberField;
            }
            set {
                this.efilingNumberField = value;
                this.RaisePropertyChanged("efilingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public fee fee {
            get {
                return this.feeField;
            }
            set {
                this.feeField = value;
                this.RaisePropertyChanged("fee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("plaintiffList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public party[] plaintiffList {
            get {
                return this.plaintiffListField;
            }
            set {
                this.plaintiffListField = value;
                this.RaisePropertyChanged("plaintiffList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
    public partial class civilFilingRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bulkFilingPacket bulkFilingPacketField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bulkFilingPacket bulkFilingPacket {
            get {
                return this.bulkFilingPacketField;
            }
            set {
                this.bulkFilingPacketField = value;
                this.RaisePropertyChanged("bulkFilingPacket");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/", ConfigurationName="CivilFilingServiceReference.CivilFilingWS")]
    public interface CivilFilingWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/submitCivilFilingR" +
            "equest", ReplyAction="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/submitCivilFilingR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CivilFilingClient.CivilFilingServiceReference.ECourtsCivilServiceException), Action="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/submitCivilFiling/" +
            "Fault/ECourtsCivilServiceException", Name="ECourtsCivilServiceException")]
        [System.ServiceModel.FaultContractAttribute(typeof(CivilFilingClient.CivilFilingServiceReference.Exception), Action="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/submitCivilFiling/" +
            "Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CivilFilingClient.CivilFilingServiceReference.submitCivilFilingResponse submitCivilFiling(CivilFilingClient.CivilFilingServiceReference.submitCivilFilingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/submitCivilFilingR" +
            "equest", ReplyAction="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/submitCivilFilingR" +
            "esponse")]
        System.Threading.Tasks.Task<CivilFilingClient.CivilFilingServiceReference.submitCivilFilingResponse> submitCivilFilingAsync(CivilFilingClient.CivilFilingServiceReference.submitCivilFilingRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/getCivilFilingStat" +
            "usRequest", ReplyAction="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/getCivilFilingStat" +
            "usResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CivilFilingClient.CivilFilingServiceReference.ECourtsCivilServiceException), Action="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/getCivilFilingStat" +
            "us/Fault/ECourtsCivilServiceException", Name="ECourtsCivilServiceException")]
        [System.ServiceModel.FaultContractAttribute(typeof(CivilFilingClient.CivilFilingServiceReference.Exception), Action="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/getCivilFilingStat" +
            "us/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CivilFilingClient.CivilFilingServiceReference.getCivilFilingStatusResponse getCivilFilingStatus(CivilFilingClient.CivilFilingServiceReference.getCivilFilingStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/getCivilFilingStat" +
            "usRequest", ReplyAction="http://webservice.civilfiling.ecourts.ito.aoc.nj/CivilFilingWS/getCivilFilingStat" +
            "usResponse")]
        System.Threading.Tasks.Task<CivilFilingClient.CivilFilingServiceReference.getCivilFilingStatusResponse> getCivilFilingStatusAsync(CivilFilingClient.CivilFilingServiceReference.getCivilFilingStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="submitCivilFiling", WrapperNamespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/", IsWrapped=true)]
    public partial class submitCivilFilingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CivilFilingClient.CivilFilingServiceReference.civilFilingRequest arg0;
        
        public submitCivilFilingRequest() {
        }
        
        public submitCivilFilingRequest(CivilFilingClient.CivilFilingServiceReference.civilFilingRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="submitCivilFilingResponse", WrapperNamespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/", IsWrapped=true)]
    public partial class submitCivilFilingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CivilFilingClient.CivilFilingServiceReference.civilFilingResponse @return;
        
        public submitCivilFilingResponse() {
        }
        
        public submitCivilFilingResponse(CivilFilingClient.CivilFilingServiceReference.civilFilingResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCivilFilingStatus", WrapperNamespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/", IsWrapped=true)]
    public partial class getCivilFilingStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CivilFilingClient.CivilFilingServiceReference.civilFilingRequest arg0;
        
        public getCivilFilingStatusRequest() {
        }
        
        public getCivilFilingStatusRequest(CivilFilingClient.CivilFilingServiceReference.civilFilingRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCivilFilingStatusResponse", WrapperNamespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/", IsWrapped=true)]
    public partial class getCivilFilingStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.civilfiling.ecourts.ito.aoc.nj/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CivilFilingClient.CivilFilingServiceReference.civilFilingResponse @return;
        
        public getCivilFilingStatusResponse() {
        }
        
        public getCivilFilingStatusResponse(CivilFilingClient.CivilFilingServiceReference.civilFilingResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CivilFilingWSChannel : CivilFilingClient.CivilFilingServiceReference.CivilFilingWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CivilFilingWSClient : System.ServiceModel.ClientBase<CivilFilingClient.CivilFilingServiceReference.CivilFilingWS>, CivilFilingClient.CivilFilingServiceReference.CivilFilingWS {
        
        public CivilFilingWSClient() {
        }
        
        public CivilFilingWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CivilFilingWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CivilFilingWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CivilFilingWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CivilFilingClient.CivilFilingServiceReference.submitCivilFilingResponse CivilFilingClient.CivilFilingServiceReference.CivilFilingWS.submitCivilFiling(CivilFilingClient.CivilFilingServiceReference.submitCivilFilingRequest request) {
            return base.Channel.submitCivilFiling(request);
        }
        
        public CivilFilingClient.CivilFilingServiceReference.civilFilingResponse submitCivilFiling(CivilFilingClient.CivilFilingServiceReference.civilFilingRequest arg0) {
            CivilFilingClient.CivilFilingServiceReference.submitCivilFilingRequest inValue = new CivilFilingClient.CivilFilingServiceReference.submitCivilFilingRequest();
            inValue.arg0 = arg0;
            CivilFilingClient.CivilFilingServiceReference.submitCivilFilingResponse retVal = ((CivilFilingClient.CivilFilingServiceReference.CivilFilingWS)(this)).submitCivilFiling(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CivilFilingClient.CivilFilingServiceReference.submitCivilFilingResponse> CivilFilingClient.CivilFilingServiceReference.CivilFilingWS.submitCivilFilingAsync(CivilFilingClient.CivilFilingServiceReference.submitCivilFilingRequest request) {
            return base.Channel.submitCivilFilingAsync(request);
        }
        
        public System.Threading.Tasks.Task<CivilFilingClient.CivilFilingServiceReference.submitCivilFilingResponse> submitCivilFilingAsync(CivilFilingClient.CivilFilingServiceReference.civilFilingRequest arg0) {
            CivilFilingClient.CivilFilingServiceReference.submitCivilFilingRequest inValue = new CivilFilingClient.CivilFilingServiceReference.submitCivilFilingRequest();
            inValue.arg0 = arg0;
            return ((CivilFilingClient.CivilFilingServiceReference.CivilFilingWS)(this)).submitCivilFilingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CivilFilingClient.CivilFilingServiceReference.getCivilFilingStatusResponse CivilFilingClient.CivilFilingServiceReference.CivilFilingWS.getCivilFilingStatus(CivilFilingClient.CivilFilingServiceReference.getCivilFilingStatusRequest request) {
            return base.Channel.getCivilFilingStatus(request);
        }
        
        public CivilFilingClient.CivilFilingServiceReference.civilFilingResponse getCivilFilingStatus(CivilFilingClient.CivilFilingServiceReference.civilFilingRequest arg0) {
            CivilFilingClient.CivilFilingServiceReference.getCivilFilingStatusRequest inValue = new CivilFilingClient.CivilFilingServiceReference.getCivilFilingStatusRequest();
            inValue.arg0 = arg0;
            CivilFilingClient.CivilFilingServiceReference.getCivilFilingStatusResponse retVal = ((CivilFilingClient.CivilFilingServiceReference.CivilFilingWS)(this)).getCivilFilingStatus(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CivilFilingClient.CivilFilingServiceReference.getCivilFilingStatusResponse> CivilFilingClient.CivilFilingServiceReference.CivilFilingWS.getCivilFilingStatusAsync(CivilFilingClient.CivilFilingServiceReference.getCivilFilingStatusRequest request) {
            return base.Channel.getCivilFilingStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<CivilFilingClient.CivilFilingServiceReference.getCivilFilingStatusResponse> getCivilFilingStatusAsync(CivilFilingClient.CivilFilingServiceReference.civilFilingRequest arg0) {
            CivilFilingClient.CivilFilingServiceReference.getCivilFilingStatusRequest inValue = new CivilFilingClient.CivilFilingServiceReference.getCivilFilingStatusRequest();
            inValue.arg0 = arg0;
            return ((CivilFilingClient.CivilFilingServiceReference.CivilFilingWS)(this)).getCivilFilingStatusAsync(inValue);
        }
    }
}
